Ship all

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,27 +35,40 @@ jobs:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         yarn deploy
-    - name: Cleanup artifacts
-      if: matrix.os != 'windows-latest'
-      run: |
-        ls -la dist
-        mkdir artifacts
-        cp -r "dist/(*.exe,*.deb,*.AppImage,*.dmg)" artifacts || true
-        ls -la artifacts
-    - name: Cleanup artifacts Win
-      if: matrix.os == 'windows-latest'
-      run: |
-        mkdir artifacts
-        cp -r dist/*.exe artifacts
+    # - name: Cleanup artifacts
+    #   if: matrix.os != 'windows-latest'
+    #   run: |
+    #     ls -la dist
+    #     mkdir artifacts
+    #     cp -r "dist/(*.exe,*.deb,*.AppImage,*.dmg)" artifacts || true
+    #     ls -la artifacts
+    # - name: Cleanup artifacts Win
+    #   if: matrix.os == 'windows-latest'
+    #   run: |
+    #     mkdir artifacts
+    #     cp -r dist/*.exe artifacts
+    # - name: Upload artifacts
+    #   uses: actions/upload-artifact@v1
+    #   with:
+    #     name: ${{matrix.os}}
+    #     path: artifacts
+    # - name: Release
+    #   uses: softprops/action-gh-release@v1
+    #   if: startsWith(github.ref, 'refs/tags/')
+    #   with:
+    #     files: "artifacts/**"
+    #   env:
+    #     GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
+
     - name: Upload artifacts
       uses: actions/upload-artifact@v1
       with:
         name: ${{matrix.os}}
-        path: artifacts
+        path: dist
     - name: Release
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
-        files: "artifacts/**"
+        files: "dist/**"
       env:
         GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
